### ISSUE TITLE
Add Event Feedback model

### ISSUE THREAD

**Issue by Chirag-Mathur** [iiitv/club_calendar#16]
### I understand and confirm the below statements

- [x] I have read the [Wiki](https://github.com/iiitv/club_calender/wiki) and I understand the concept and structure of the app.
- [x] The functionality has not already been covered in an existing issue.
- [x] Assign this issue to me (I want to work on this).
	- [x] I ensure that I am not already assigned to 2 or more issues.
- [x] I will send my PR only after I'm assigned to this issue by any maintainer.
- [x] I understand that I will be unassigned from this issue if I fail to send a PR for this within 3 days.

**Comment by Chirag-Mathur** [comment]
@iiitv/project-maintainers  I want to on this issue.

**Comment by thecodepapaya** [comment]
GFI @Chirag-Mathur

**Comment by Chirag-Mathur** [comment]
@iiitv/project-maintainers  Will this model be dependent on events model, to check the available attributes of a particular event?

**Comment by thecodepapaya** [comment]
Since #23 is now merged, this issue is no longer blocked.

**Comment by vikiwarrior** [comment]
#68 closes this issue
