### ISSUE TITLE
Add EventScreenUI

### ISSUE THREAD

**Issue by Chirag-Mathur** [iiitv/club_calendar#19]
### I understand and confirm the below statements

- [x] I have read the [Wiki](https://github.com/iiitv/club_calender/wiki) and I understand the concept and structure of the app.
- [x] The functionality has not already been covered in an existing issue.
- [x] Assign this issue to me (I want to work on this).
	- [x] I ensure that I am not already assigned to 2 or more issues.
- [x] I will send my PR only after I'm assigned to this issue by any maintainer.
- [x] I understand that I will be unassigned from this issue if I fail to send a PR for this within 3 days.

**Comment by Chirag-Mathur** [comment]
@iiitv/project-maintainers I want to work on this issue.

**Comment by thecodepapaya** [comment]
GFI @Chirag-Mathur

**Comment by Chirag-Mathur** [comment]
@iiitv/project-maintainers I want to work on this issue.

**Comment by thecodepapaya** [comment]
GFI @Chirag-Mathur

**Comment by thecodepapaya** [comment]
@Chirag-Mathur are you still working on this?

**Comment by Chirag-Mathur** [comment]
@thecodepapaya Yes Sir, I am working on this. The drawer is completed, only the cards are left.

**Comment by AkhileshManda** [comment]
@iiitv/project-maintainers @iiitv/flutter-maintainers I want to work on this issue.

**Comment by vikiwarrior** [comment]
GFI @AkhileshManda
