### ISSUE TITLE
Add Cloud Messaging Handler

### ISSUE THREAD

**Issue by Monik09** [iiitv/club_calendar#25]
### I understand and confirm the below statements

- [x] I have read the [Wiki](https://github.com/iiitv/club_calender/wiki) and I understand the concept and structure of the app.
- [x] The functionality has not already been covered in an existing issue.
- [x] Assign this issue to me (I want to work on this).
	- [x] I ensure that I am not already assigned to 2 or more issues.
- [x] I will send my PR only after I'm assigned to this issue by any maintainer.
- [x] I understand that I will be unassigned from this issue if I fail to send a PR for this within 3 days.

**Comment by thecodepapaya** [comment]
GFI @Monik09

**Comment by Monik09** [comment]
@thecodepapaya sir, do I need to show the message on temporary homepage which was sent as notification.

**Comment by thecodepapaya** [comment]
No, for the time being just print in on the console.
