### ISSUE TITLE
Add CrashLytics Handler

### ISSUE THREAD

**Issue by Monik09** [iiitv/club_calendar#28]
With the help of crashlytics we will be able to know bugs and issues which might be making the app unstable and I will be using <a href=https://pub.dev/packages/firebase_crashlytics>Flutter crashlytics package</a> developed by google.

### I understand and confirm the below statements

- [x] I have read the [Wiki](https://github.com/iiitv/club_calender/wiki) and I understand the concept and structure of the app.
- [x] The functionality has not already been covered in an existing issue.
- [x] Assign this issue to me (I want to work on this).
	- [x] I ensure that I am not already assigned to 2 or more issues.
- [x] I will send my PR only after I'm assigned to this issue by any maintainer.
- [ ] I understand that I will be unassigned from this issue if I fail to send a PR for this within 3 days.

**Comment by Monik09** [comment]
@iiitv/project-maintainers I want to work on this issue.

**Comment by aashutoshrathi** [comment]
Hey, sure you can work on this!
Can you add more description about `CrashLytics` here?

**Comment by Monik09** [comment]
@aashutoshrathi, done👍

**Comment by thecodepapaya** [comment]
GFI @Monik09
