### ISSUE TITLE
Define styles globally

### ISSUE THREAD

**Issue by thecodepapaya** [iiitv/club_calendar#31]
Create a file `styles.dart` in `lib` folder containing all the styles we would use in the app in different places. This way we won't have to define styles in all the different places in the UI.
For instance, this file could contain all the different colours we'd use in the app like
- background colour
- primary colours
- secondary colours

This file would also include all the different styles for consistent reusable components like 
- text style
  - styles for the app title
  - styles for headings
  - styles for body
  - other text styles which are used consistently in the app 
- shadows
- elevations
- icon styles

This list is just for reference and not exhaustive.

**Comment by Monik09** [comment]
@thecodepapaya sir, I want to work on this issue.

**Comment by thecodepapaya** [comment]
GFI @Monik09
