### ISSUE TITLE
Sign-in state lost after restarting the app

### ISSUE THREAD

**Issue by thecodepapaya** [iiitv/club_calendar#32]
**Describe the bug**
The sign-in state of the user must always be synced with the server state. Upon doing a hot restart after signing-in, the login screen is shown i.e sign-in state is lost and is out of sync with the firebase login state as can be seen in the console.

**To Reproduce**
Steps to reproduce the behaviour:
1. Pull the latest changes from the master branch
2. Build and run the app
3. Sign in with a google account
4. Wait for the home page to appear and then do a **hot restart** 
5. The login page is shown again
6. Also, if you close and reopen the app, the login screen is displayed again instead of the home screen.

**Expected behaviour**
Even after doing a hot restart, if the user is logged in, the home should be displayed and not the login screen since the login state must be in sync with the server. If the user closes and reopens the app without signing out, the home screen should be displayed instead of the login screen.

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: NA
 - Browser NA
 - Version NA

**Smartphone (please complete the following information):**
 - Device: Pixel 3a emulator
 - OS: Android
 - Browser: NA
 - Version: 29

**Additional context**
NA

**Proposed Solution**
Using a stream-based approach might solve this problem. A stream builder could be employed to continuously listen to the auth state of the user and display an appropriate screen depending on the state.

**Comment by Monik09** [comment]
@thecodepapaya sir, i want to work on this issue.

**Comment by thecodepapaya** [comment]
GFI @Monik09
