### ISSUE TITLE
Add .editorconfig file

### ISSUE THREAD

**Issue by nlok5923** [iiitv/club_calendar#36]
**Is your feature request related to a problem? Please describe.**
just to maintain indentation uniformity with code.

**Describe the solution you'd like**
editorconfig file will help to maintain uniform indentation in pr submitted by multiple contributors.

**Describe alternatives you've considered**
Adding an .editorconfig file

**Comment by nlok5923** [comment]
if this issue is valid @iiitv/project-maintainers i would like to work on it,

**Comment by aashutoshrathi** [comment]
@nlok5923 GFI
Make sure you understand every line you add or not add
