### ISSUE TITLE
Club Calendar logo error and travis badge in README

### ISSUE THREAD

**Issue by Monik09** [iiitv/club_calendar#45]
**Describe the bug**
In Readme.md file, the logo of club calendar is not displaying correctly. The travis badge is also not showing the status.
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to [club calendar](https://github.com/iiitv/club_calendar)
2. Scroll down to Readme
3. See error

**Expected behaviour**
The logo of club calendar should be displayed and the build status of repo too.
![image](https://user-images.githubusercontent.com/52850691/94335126-fffc8b80-fff6-11ea-921d-c465fdb7402e.png)

**Screenshots**
Current Readme:
![image](https://user-images.githubusercontent.com/52850691/94335145-36d2a180-fff7-11ea-85f3-baee35207c60.png)

**Desktop (please complete the following information):**
 - OS: ALL
 - Browser ALL
 - Version ALL

**Smartphone (please complete the following information):**
 - Device: ALL
 - OS: ALL
 - Browser ALL
 - Version ALL

**Additional context**
The problem may be with the file name or location.

**Comment by Monik09** [comment]
@iiitv/project-maintainers can i work on this issue.

**Comment by thecodepapaya** [comment]
Also, figure out why the Travis status is unknown and try to fix it the Readme

**Comment by thecodepapaya** [comment]
GFI @Monik09
