### ISSUE TITLE
Replace "Add" Icon button with "Show Details" Elevated button.

### ISSUE THREAD

**Issue by marizvi** [iiitv/club_calendar#56]
The existing homepage of the app is quite boring, I would like to take the opportunity to make it more impressive and attractive for the users.
So in order to achieve this task I would love to start with changing add Icon button on homepage to an impressive elevated Button with text displaying the actual feature of that button which is to Show Event details. 

I would be glad if you assign me this issue to work on it under Contribute-athon'21.

**Comment by vikiwarrior** [comment]
Go ahead @marizvi .Create more buttons for upcoming pages.The current hompage is temporary so no need to adhere to the neumorphic design guidelines.
